server:
    endpoint: opc.tcp://0.0.0.0:4840
    name: My Test Server
    namespaces:
        - http://my.namespace
        - http://someother.namespace
nodes:
    - nodeid: ns=1;i=1234
      name: MyVar
      value: 15
      type: variable
    - nodeid: ns=1;i=431
      name: YoursVar
      value: 11
      type: variable